# Generated by Django 2.2.7 on 2019-12-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191208_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default=False, help_text='Age of squirrel', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], default=False, help_text='location of squirrel', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Primary_fur_color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('Black', 'Black'), ('Cinnamon', 'Cinnamon')], default=False, help_text='Primary fur color of squirrel', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Specific_location',
            field=models.CharField(default=False, help_text='Specific location of squirrel', max_length=100),
        ),
    ]
